[package]
name = "scottricity/color-utils"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Some useful utilities for colors."

[dependencies]
